Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -27,19 +27,25 @@ jobs:
       with:
         go-version: '1.20'
 
-    - name: Debug- Show current directory and app path
+    - name: Debug-- Show current directory and app path
       run: |
         echo "Current directory: $(pwd)"
-        echo "App directory: src/${{ github.event.inputs.app }}"
-        ls src/${{ github.event.inputs.app }}  # Listar el contenido para verificar si existe
+        echo "App selected: ${{ github.event.inputs.app }}"
+        APP_DIR="src/${{ github.event.inputs.app }}"
+        echo "App directory: $APP_DIR"
+        ls "$APP_DIR"  # Listar el contenido para verificar si existe
 
     - name: Build and run Docker container
       run: |
         APP_DIR="src/${{ github.event.inputs.app }}"
         echo "Building Docker image from $APP_DIR"
-        echo "Contents of $APP_DIR:"
-        ls "$APP_DIR"  # Asegurarse de que el directorio tiene lo que se espera
-
+        
+        # Verificar que APP_DIR no esté vacío
+        if [ -z "$APP_DIR" ]; then
+          echo "Error: APP_DIR is empty"
+          exit 1
+        fi
+        
         # Construir la imagen de Docker
-        docker build -t "${{ github.event.inputs.app }}" "$APP_DIR"  # Especifica el directorio de la app
+        docker build -t "${{ github.event.inputs.app }}" "$APP_DIR"
         docker run --rm "${{ github.event.inputs.app }}"
