Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -56,21 +56,38 @@ jobs:
           
           if [ "${{ env.event_type }}" == "push" ]; then
             echo "Running all applications because of a push event..."
-            for app in "${apps[@]}"; do
-              echo "Building and running $app..."
-              # Verificamos si app_to_run está vacío
-              if [ -z "${{ env.app_to_run }}" ]; then
-                echo "No relevant changes detected. Running all applications..."
-                for app in "${apps[@]}"; do
-                  echo "Building and running $app..."
-                  echo "tener los comandos para compilar y ejecutar la app"
-                done
+            # Obtener las aplicaciones en el directorio src/
+            apps=($(ls src/))
+            echo "Subdirectorios: ${{ apps }}"
+            # Filtrar las aplicaciones que están en los inputs y en el listado de subdirectorios
+            filtered_apps=()
+            echo "filtered_apps : ${{ filtered_apps }}"
+            for input_app in ${{ github.event.inputs.app_name }}; do
+              if [[ " ${apps[@]} " =~ " ${input_app} " ]]; then
+                filtered_apps+=("$input_app")
               else
+                echo "Warning: La aplicación especificada '${input_app}' no se encuentra en el directorio src/."
+              fi
+            done
+        
+            # Comprobar si no hay aplicaciones filtradas
+            if [ ${#filtered_apps[@]} -eq 0 ]; then
+              echo "Error: No hay aplicaciones válidas para ejecutar."
+              exit 1
+            fi
+            # Verificamos si app_to_run está vacío. Si lo está hay que ejecutar todas
+            if [ -z "${{ env.app_to_run }}" ]; then
+              echo "No relevant changes detected. Running all applications..."
+              echo "Aplicaciones a ejecutar: ${filtered_apps[@]}"
+              for app in "${filtered_apps[@]}"; do
+                echo "Building and running $app..."
+                echo "tener los comandos para compilar y ejecutar la app: ${{ app }}"
+              done
+            else
                 echo "Relevant changes detected. Running only the specified application: ${{ env.app_to_run }}"
                 echo "Building and running only the selected application: ${{ env.app_to_run }}"
                 echo "Tener los comandos para compilar y ejecutar solo la app seleccionada : ${{ env.app_to_run }}"
-              fi
-            done
+            fi
           elif [ "${{ env.event_type }}" == "workflow_dispatch" ]; then
             echo "Running selected application: ${{ github.event.inputs.app_name }}"
             if [ "${{ github.event.inputs.app_name }}" == "" ]; then
